<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aife.Application\Aife.Application.csproj" />
    <ProjectReference Include="..\Aife.Domain\Aife.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Polly.Extensions.Http" />
  </ItemGroup>

</Project>
